### PR TITLE
Fix PATH bug (Windows)

### PR DESCRIPTION
**Pull request by Manouchehri**
Got a bug report from @brianwanjir that he was having issues on Windows, this should fix it. Probably the same issue as reported in #6.

### CODE REVIEW

**Comment by Manouchehri** [comment]
Confirmed by @brianwanjir that this does indeed fix Windows' issue in locating `core.jar` and `javase.jar`. Still investigating what the issue is on OS X.

**Comment by chuckytah** [comment]
@Manouchehri you said "Still investigating what the issue is on OS X." have you found something?

**Comment by Manouchehri** [comment]
I haven't done anything yet. I don't have a Mac, but if you're willing to
check a few things for me I can probably figure it out.

**Comment by chuckytah** [comment]
@Manouchehri I could try, yes

**Pull request merged**
